### ISSUE TITLE
Are there any way to watch videos for non Stanford students?

### ISSUE THREAD

**Issue by bogdan-evtushenko** [deepgenerativemodels/notes#30]

**Comment by lin7275** [comment]
perhaps donate a library?

**Comment by pratikshappai** [comment]
yes, this would be very helpful, thanks!

**Comment by ermonste** [comment]
Videos are available here:

https://www.youtube.com/playlist?list=PLoROMvodv4rPOWA-omMM6STXaWW4FvJT8
